/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON Schema для состояния спиральной секции (SpiralSectionState), расширяющая базовую схему секции
 */
export type SpiralSectionState = BaseSectionState & {
  Lift: LIFT_STATE;
  LiftTrap?: DOOR_STATE;
  DeliveryBox: DELIVERY_BOX_STATE;
  /**
   * Массив состояний ячеек спиральной секции
   */
  Cells?: TYPE_SPIRAL_CELL[];
  [k: string]: unknown;
};

/**
 * JSON Schema для базового состояния секции (BaseSectionState)
 */
export interface BaseSectionState {
  /**
   * Наименование секции (например, 'spiral', 'postomat')
   */
  Name: string;
  IsAvailable: AVAILABLE_STATE;
  Door?: DOOR_STATE;
  Status: SECTION_STATUS;
  Command?: COMMAND_STATE;
  /**
   * Массив состояний строк (полок) секции
   */
  Rows: LINE_STATE[];
  /**
   * Массив состояний столбцов секции
   */
  Cols: LINE_STATE[];
  /**
   * Массив состояний ячеек секции
   */
  Cells: TYPE_CELL[];
  /**
   * Массив транзакционных состояний ячеек
   */
  CellsTransact: TRANSACT_STATE[];
  /**
   * Массив флагов доступности моторесурса по ячейкам
   */
  Resourse_available: AVAILABLE_STATE[];
  /**
   * Словарь состояний модулей ввода-вывода (IO)
   */
  IO: {
    [k: string]: TYPE_IO;
  };
}
/**
 * Объект состояния ячейки секции (Status, Action)
 */
export interface TYPE_CELL {
  Status: CELL_STATE;
  Action: CELL_ACTION;
}
/**
 * Объект состояния и конфигурации модуля ввода-вывода (IO)
 */
export interface TYPE_IO {
  /**
   * Имя модуля ввода-вывода
   */
  name: string;
  state: IO_STATE;
  /**
   * Массив состояний портов IO модуля
   */
  ports: IO_PORT_STATE[];
}
/**
 * Объект состояния ячейки спиральной секции (Status, Action)
 */
export interface TYPE_SPIRAL_CELL {
  Status: SPIRAL_CELL_STATE | CELL_STATE;
  Action: CELL_ACTION;
}

/**
 * Флаг доступности (YES - доступно/в норме, NO - недоступно/исчерпано)
 */
export enum AVAILABLE_STATE {
  YES = "YES",
  NO = "NO"
}
/**
 * Состояние сервисной двери секции (CLOSED - закрыта, OPEN - открыта)
 */
export enum DOOR_STATE {
  CLOSED = "CLOSED",
  OPEN = "OPEN"
}
/**
 * Статус выполнения операций секции (IDLE - простой, DISPENSE - выдача ТМЦ, DELIVERY - доставка, BLOCKED - заблокирована, LOADING - загрузка ТМЦ)
 */
export enum SECTION_STATUS {
  IDLE = "IDLE",
  DISPENSE = "DISPENSE",
  DELIVERY = "DELIVERY",
  BLOCKED = "BLOCKED",
  LOADING = "LOADING"
}
/**
 * Состояние выполнения команд (IDLE - ожидание команды, COMMAND - выполнение команды, BLOCKED - заблокировано)
 */
export enum COMMAND_STATE {
  IDLE = "IDLE",
  COMMAND = "COMMAND",
  BLOCKED = "BLOCKED"
}
/**
 * Состояние строки или столбца секции (OK - в норме, BLOCKED - заблокирован)
 */
export enum LINE_STATE {
  OK = "OK",
  BLOCKED = "BLOCKED"
}
/**
 * Флаги состояния ячейки (OK - штатно, OVERLOAD_I - повышенный ток, OVERLOAD_V - повышенное напряжение, BLOCKED - заблокирована, ERROR - ошибка, SERVICE - обслуживание, ERR_TAMPER - ошибка тампера, ERR_TAMPER_BAD_POS - некорректная позиция, ACTUATOR_SHORT_CIRCUIT - КЗ актуатора, ACTUATOR_NO_POWER - нет питания, ERR_MECHANICAL - механическая поломка, OVERLOAD - перегрузка, NOT_CLOSED - ячейка открыта слишком долго)
 */
export enum CELL_STATE {
  OK = "OK",
  OVERLOAD_I = "OVERLOAD_I",
  OVERLOAD_V = "OVERLOAD_V",
  BLOCKED = "BLOCKED",
  ERROR = "ERROR",
  SERVICE = "SERVICE",
  ERR_TAMPER = "ERR_TAMPER",
  ERR_TAMPER_BAD_POS = "ERR_TAMPER_BAD_POS",
  ACTUATOR_SHORT_CIRCUIT = "ACTUATOR_SHORT_CIRCUIT",
  ACTUATOR_NO_POWER = "ACTUATOR_NO_POWER",
  ERR_MECHANICAL = "ERR_MECHANICAL"
}
/**
 * Флаги состояния действия ячейки (IDLE - закрыта/в ждущем режиме, ACTION - отрабатывает команду выдачи, OPEN - открыта, NOT_CLOSED - открыта слишком долго)
 */
export enum CELL_ACTION {
  IDLE = "IDLE",
  ACTION = "ACTION",
  OPEN = "OPEN",
  NOT_CLOSED = "NOT_CLOSED"
}
/**
 * Транзакционное состояние выполнения операции над ячейкой (OK - готова, EXECUTING - выполняется, COMPLETED - завершена, WARNING - предупреждение)
 */
export enum TRANSACT_STATE {
  OK = "OK",
  EXECUTING = "EXECUTING",
  COMPLETED = "COMPLETED",
  WARNING = "WARNING"
}
/**
 * Состояние модуля ввода-вывода (OK - в норме, ERR_NO_LINK - потеряно соединение с IO модулем)
 */
export enum IO_STATE {
  OK = "OK",
  ERR_NO_LINK = "ERR_NO_LINK"
}
/**
 * Состояние порта модуля ввода-вывода (OK - в норме, ERROR - порт повреждён)
 */
export enum IO_PORT_STATE {
  OK = "OK",
  ERROR = "ERROR"
}
/**
 * Флаги состояния лифта (OK - в норме, OVERLOAD - перегрузка, BLOCKED - недоступен, SHORT_CIRCUIT - короткое замыкание, NO_POWER - отсутствует питание, ERR_TAMPER - тампер вышел из строя, ERR_LEVEL - неисправен датчик уровня, ERR_MECHANICAL - механическая поломка)
 */
export enum LIFT_STATE {
  OK = "OK",
  OVERLOAD = "OVERLOAD",
  BLOCKED = "BLOCKED",
  SHORT_CIRCUIT = "SHORT_CIRCUIT",
  NO_POWER = "NO_POWER",
  ERR_TAMPER = "ERR_TAMPER",
  ERR_LEVEL = "ERR_LEVEL",
  ERR_MECHANICAL = "ERR_MECHANICAL"
}
/**
 * Флаги состояния лючка выдачи (OPENED - люк открыт, CLOSED - люк закрыт, ERR_MECHANICAL - механическая поломка)
 */
export enum DELIVERY_BOX_STATE {
  OPENED = "OPENED",
  CLOSED = "CLOSED",
  ERR_MECHANICAL = "ERR_MECHANICAL"
}
/**
 * Флаги состояния ячейки спиральной секции (OK - в норме, OPENING - открывается, OVERLOAD_I - повышенный ток, OVERLOAD_V - повышенное напряжение, BLOCKED - заблокирована, ERROR - ошибка, SERVICE - обслуживание, ERR_TAMPER - ошибка тампера, ERR_TAMPER_BAD_POS - некорректная позиция, ACTUATOR_SHORT_CIRCUIT - КЗ актуатора, ACTUATOR_NO_POWER - нет питания, ERR_MECHANICAL - механическая поломка, OVERLOAD - перегрузка, TAMPER_BAD_POS_ERROR - ошибка начального положения тампера, NOT_CLOSED - ячейка открыта слишком долго)
 */
export enum SPIRAL_CELL_STATE {
  OK = "OK",
  OPENING = "OPENING",
  OVERLOAD_I = "OVERLOAD_I",
  OVERLOAD_V = "OVERLOAD_V",
  BLOCKED = "BLOCKED",
  ERROR = "ERROR",
  SERVICE = "SERVICE",
  ERR_TAMPER = "ERR_TAMPER",
  ERR_TAMPER_BAD_POS = "ERR_TAMPER_BAD_POS",
  ACTUATOR_SHORT_CIRCUIT = "ACTUATOR_SHORT_CIRCUIT",
  ACTUATOR_NO_POWER = "ACTUATOR_NO_POWER",
  ERR_MECHANICAL = "ERR_MECHANICAL",
  OVERLOAD = "OVERLOAD",
  TAMPER_BAD_POS_ERROR = "TAMPER_BAD_POS_ERROR",
  NOT_CLOSED = "NOT_CLOSED"
}
