module.exports = [
    { Name: "process", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary", InitOrder: 10, Protocol: 'sys', PrimaryBus: 'sysBus', BusList: ['logBus', 'mdbBus', 'dataBus'], EventList: ['process-config-system-get', 'process-ws-connect-done', 'process-mqtt-connect-done', 'process-rpi-connect-done'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'Process description'},
    { Name: "logger", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary", InitOrder: 30, Protocol: 'sys', PrimaryBus: 'logBus', BusList: ['sysBus', 'mdbBus', 'dataBus', 'rpiBus', 'lhpBus', 'mqttBus'], EventList: ['logger-log', 'all-init-stage1-set'], AdvancedOptions: {port: 5142, console: true}, Dependency: ['srvService', 'graylog2'], Description: 'Logger description'},
    { Name: "proxylogger", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary", InitOrder: 35, Protocol: 'sys', PrimaryBus: 'logBus', BusList: ['sysBus', 'mdbBus', 'dataBus', 'rpiBus', 'lhpBus', 'mqttBus'], EventList: ['logger-log', 'all-init-stage1-set'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'Proxy logger description'},
    { Name: "proxychannel", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary", InitOrder: 38, Protocol: 'sys', PrimaryBus: 'dataBus', BusList: ['sysBus', 'dataBus', 'logBus'], EventList: ['all-init-stage1-set'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'Proxy channel description'},
    { Name: "providermdb", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary", InitOrder: 20, Protocol: 'sys', PrimaryBus: 'mdbBus', BusList: ['logBus', 'sysBus'], EventList: ['event1', 'event2', 'event3', 'event4'], AdvancedOptions: {}, Dependency: ['srvService', 'mongodb'], Description: 'Provider description'},
    { Name: "dm", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "primary", InitOrder: 40, Protocol: 'sys', PrimaryBus: 'sysBus', BusList: ['logBus', 'mdbBus', 'dataBus'], EventList: ['all-init-stage1-set', 'all-close', 'all-connections-done', 'mqttclient-send'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'Device Manager description'},
    
    { Name: "modbusclienttcp", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary", InitOrder: 130, Protocol: 'modbustcp', PrimaryBus: 'modbustcpBus', BusList: ['logBus', 'sysBus'], EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'modbusclienttcp-send'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'Modbus client description'},
    { Name: "proxymodbustcp", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary", InitOrder: 140, Protocol: 'modbustcp', PrimaryBus: 'modbustcpBus', BusList: ['logBus', 'sysBus'], EventList: ['all-init-stage1-set', 'test-connect', 'proxymodbustcp-msg-get', 'proxymodbustcp-msg-get'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'ProxyModbus description'},
    { Name: "modbusclientrot", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary", InitOrder: 145, Protocol: 'modbusrot', PrimaryBus: 'modbusrotBus', BusList: ['logBus', 'sysBus'], EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'modbusclientrot-send', 'modbusled-source-toss'], AdvancedOptions: {}, Dependency: ['srvModbusBase'], Description: 'Modbus client description'},
    { Name: "proxymodbusrot", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary", InitOrder: 146, Protocol: 'modbusrot', PrimaryBus: 'modbusrotBus', BusList: ['logBus', 'sysBus'], EventList: ['all-init-stage1-set', 'test-connect', 'proxymodbusrot-msg-get', 'proxymodbusrot-msg-get'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'ProxyModbus description'},
    

   // { Name: "modbusled", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "exploitary", InitOrder: 147, Protocol: 'mled', PrimaryBus: 'modbusledBus', BusList: ['logBus', 'sysBus', 'modbusrotBus'], EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'modbusclientrot-send'], AdvancedOptions: {host: 'modbusclientrot'}, Dependency: ['srvService'], Description: 'ModbusLED client description'},
    // { Name: "proxymodbusled", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary", InitOrder: 148, Protocol: 'mled', PrimaryBus: 'modbusledBus', BusList: ['logBus', 'sysBus'], EventList: ['all-init-stage1-set', 'test-connect', 'proxymodbusled-msg-get'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'ProxyModbusLED description'},
    // { Name: "snmpclient", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary", InitOrder: 150, Protocol: 'snmp', PrimaryBus: 'snmpBus', BusList: ['logBus', 'sysBus'], EventList: ['all-init-stage1-set', 'test-connect', 'all-disconnect', 'snmpclient-send'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'SNMP client description'},
    // { Name: "proxysnmp", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary", InitOrder: 160, Protocol: 'snmp', PrimaryBus: 'snmpBus', BusList: ['logBus', 'sysBus'], EventList: ['all-init-stage1-set', 'test-connect', 'proxysnmp-msg-get', 'proxysnmp-msg-get'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'ProxySNMP description'},
    { Name: "mqttclient", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary", InitOrder: 70, Protocol: 'mqtt', PrimaryBus: 'mqttBus', BusList: ['logBus', 'sysBus'], EventList: ['all-init-stage1-set', 'all-close', 'all-connections-done', 'mqttclient-send'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'MQTT client desription'},
    { Name: "proxymqttclient", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary", InitOrder: 80, Protocol: 'mqtt', PrimaryBus: 'mqttBus', BusList: ['logBus', 'sysBus'], EventList: ['all-init-stage1-set', 'all-close', 'proxymqttclient-get-msg', 'proxymqttclient-send', 'proxymqttclient-deviceslist-get'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'Proxymqtt desription'},
    
    { Name: "mmtrxmotor",      Status: 'stopped', ErrorMsg: '', Service: null, Importance: "exploitary", InitOrder: 170, Protocol: 'mmtrxmotor', PrimaryBus: 'mmtrxmotorBus', BusList: ['logBus', 'sysBus', 'mmtrxmotorBus'], EventList: ['all-init-stage1-set', 'mmtrxmotor-cmd'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'ModbusMatrixMotor client description'},
    { Name: "proxymmtrxmotor", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 171, Protocol: 'mmtrxmotor', PrimaryBus: 'mmtrxmotorBus', BusList: ['logBus', 'mmtrxmotorBus'],           EventList: ['all-init-stage1-set', 'proxymmtrxmotor-send', 'proxymmtrxmotor-msg-get'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'ProxyModbusMatrixMotor description'},

    { Name: "mhbridge",      Status: 'stopped', ErrorMsg: '', Service: null, Importance: "exploitary", InitOrder: 175, Protocol: 'mhbridge', PrimaryBus: 'mhbridgeBus', BusList: ['logBus', 'sysBus', 'mhbridgeBus'], EventList: ['all-init-stage1-set', 'mmtrxmotor-cmd'], AdvancedOptions: { }, Dependency: ['srvService'], Description: 'ModbusHBridgeMotor client description'},
    { Name: "proxymhbridge", Status: 'stopped', ErrorMsg: '', Service: null, Importance: "auxilary",   InitOrder: 178, Protocol: 'mhbridge', PrimaryBus: 'mhbridgeBus', BusList: ['logBus', 'mhbridgeBus'],           EventList: ['all-init-stage1-set', 'proxymmtrxmotor-send', 'proxymmtrxmotor-msg-get'], AdvancedOptions: {}, Dependency: ['srvService'], Description: 'ModbusHBridgeMotor description'},
]