module.exports = [
    { ID: 24, Name: "template-mqtt-service-channel", Service: null, Status: "stopped", Importance: "application", InitOrder: 1000, Protocol: "mqtt", PrimaryBus: "dataBus", BusList: [ "sysBus", "logBus", "mdbBus", "mqttBus"], EventList: [ "all-init-stage1-set", "all-data-raw-get", "dm-deviceslist-set", "providermdb-device-config-set"], Dependency: ["srvService"], ErrorMsg: "", Description: "Служба предназначена для обеспечения работы с измерительным или испольнительным каналом по протоколу mqtt." },
        
    { ID: 24, Name: "template-modbustcp-service-channel", Service: null, Status: "stopped", Importance: "application", InitOrder: 1000, Protocol: "modbustcp", PrimaryBus: "dataBus", BusList: [ "sysBus", "logBus", "mdbBus", "modbustcpBus"], EventList: [ "all-init-stage1-set", "all-data-raw-get", "dm-deviceslist-set", "providermdb-device-config-set"], Dependency: ["srvService"], ErrorMsg: "", Description: "Служба предназначена для обеспечения работы с измерительным или испольнительным каналом по протоколу modbus." },
    // { ID: 25, Name: "template-snmp-service-channel", Service: null, Status: "stopped", Importance: "application", InitOrder: 1000, Protocol: "snmp", PrimaryBus: "dataBus", BusList: [ "sysBus", "logBus", "mdbBus", "snmpBus"], EventList: [ "all-init-stage1-set", "all-data-raw-get", "dm-deviceslist-set", "providermdb-device-config-set"], Dependency: ["srvService"], ErrorMsg: "", Description: "Служба предназначена для обеспечения работы с измерительным или испольнительным каналом по протоколу snmp." },
    // { ID: 28, Name: "template-mled-service-channel", Service: null, Status: "stopped", Importance: "application", InitOrder: 1010, Protocol: "mled", PrimaryBus: "dataBus", BusList: [ "sysBus", "logBus", "mdbBus", "modbusledBus"], EventList: [ "all-init-stage1-set", "all-data-raw-get", "dm-deviceslist-set", "providermdb-device-config-set"], Dependency: ["srvService"], ErrorMsg: "", Description: "Служба предназначена для обеспечения работы с измерительным или испольнительным каналом диодной ленты с поддержкой modbus." },
    { ID: 26, Name: "template-modbusrot-service-channel", Service: null, Status: "stopped", Importance: "application", InitOrder: 1000, Protocol: "modbusrot", PrimaryBus: "dataBus", BusList: [ "sysBus", "logBus", "mdbBus", "modbusrotBus"], EventList: [ "all-init-stage1-set", "all-data-raw-get", "dm-deviceslist-set", "providermdb-device-config-set"], Dependency: ["srvService"], ErrorMsg: "", Description: "Служба предназначена для обеспечения работы с измерительным или испольнительным каналом по протоколу modbus." },
    { ID: 29, Name: "template-mmtrxmotor-service-channel", Service: null, Status: "stopped", Importance: "application", InitOrder: 1000, Protocol: "mmtrxmotor", PrimaryBus: "dataBus", BusList: [ "sysBus", "logBus", "mdbBus", "mmtrxmotorBus"], EventList: [ "all-init-stage1-set", "all-data-raw-get", "dm-deviceslist-set", "providermdb-device-config-set"], Dependency: ["srvService"], ErrorMsg: "", Description: "Служба предназначена для обеспечения работы с измерительным или испольнительным каналом по протоколу modbus." },
    { ID: 30, Name: "template-mhbridge-service-channel", Service: null, Status: "stopped", Importance: "application", InitOrder: 1000, Protocol: "mhbridge", PrimaryBus: "dataBus", BusList: [ "sysBus", "logBus", "mdbBus", "mhbridgeBus"], EventList: [ "all-init-stage1-set", "all-data-raw-get", "dm-deviceslist-set", "providermdb-device-config-set"], Dependency: ["srvService"], ErrorMsg: "", Description: "Служба предназначена для обеспечения работы с измерительным или испольнительным каналом по протоколу modbus." }
];
